function check(condition, message) {
    if (!condition)
        throw new Error(message);
}

check(typeof QSvgRenderer === "function", "QSvgRenderer binding was not imported");
check(typeof QSvgGenerator === "function", "QSvgGenerator binding was not imported");
check(typeof QSvgWidget === "function", "QSvgWidget binding was not imported");
check(typeof QGraphicsSvgItem === "function", "QGraphicsSvgItem binding was not imported");
check(typeof QtSvg === "object" && typeof QSvg === "object",
      "QtSvg and the Qt 5 QSvg namespace alias were not imported");
if (typeof QtSvg.DisableAnimations !== "undefined") {
    check(QtSvg.DisableAnimations.valueOf() === 240,
          "QtSvg option values were not exported");
    check(QSvg.DisableAnimations.valueOf() === QtSvg.DisableAnimations.valueOf(),
          "QSvg namespace alias does not share QtSvg options");
}

var svg = '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="24" viewBox="0 0 32 24">' +
          '<rect id="background" width="32" height="24" fill="#102030"/>' +
          '<circle id="marker" cx="16" cy="12" r="6" fill="#ff0000"/>' +
          '</svg>';
var renderer = new QSvgRenderer(new QByteArray(svg));
check(renderer.isValid(), "QSvgRenderer rejected a valid in-memory document");
check(renderer.defaultSize().width() === 32 && renderer.defaultSize().height() === 24,
      "QSvgRenderer defaultSize conversion failed");
check(renderer.viewBoxF().width() === 32 && renderer.viewBoxF().height() === 24,
      "QSvgRenderer viewBox conversion failed");
renderer.setAspectRatioMode(Qt.IgnoreAspectRatio);
check(renderer.aspectRatioMode.valueOf() === Qt.IgnoreAspectRatio.valueOf(),
      "QSvgRenderer aspect-ratio mode did not round-trip");
check(renderer.elementExists("background") && renderer.elementExists("marker"),
      "QSvgRenderer element lookup failed");
check(renderer.boundsOnElement("marker").width() > 0,
      "QSvgRenderer boundsOnElement returned an empty marker");

var image = new QImage(32, 24, QImage.Format_ARGB32);
image.fill(0);
var painter = new QPainter();
check(painter.begin(image), "QPainter could not begin raster SVG rendering");
renderer.render(painter);
check(painter.end(), "QPainter could not finish raster SVG rendering");
check(((image.pixel(16, 12) >>> 24) & 255) > 0,
      "QSvgRenderer did not paint into a QImage");

var buffer = new QBuffer();
check(buffer.open(new QIODevice.OpenMode(QIODevice.ReadWrite)),
      "QBuffer could not be opened for SVG generation");
var generator = new QSvgGenerator();
generator.setOutputDevice(buffer);
generator.setSize(new QSize(32, 24));
generator.setViewBox(new QRect(0, 0, 32, 24));
generator.setTitle("QtScript SVG smoke");
generator.setDescription("generated by the Qt 6 binding");
var generatorPainter = new QPainter();
check(generatorPainter.begin(generator), "QPainter could not begin SVG generation");
generatorPainter.fillRect(new QRect(2, 3, 12, 8), new QColor(20, 40, 60));
check(generatorPainter.end(), "QPainter could not finish SVG generation");
check(buffer.size() > 200, "QSvgGenerator produced an unexpectedly small document");
buffer.seek(0);
check(buffer.readAll().toString().indexOf("<svg") !== -1,
      "QSvgGenerator output is not SVG");
buffer.close();

var widget = new QSvgWidget();
widget.load(new QByteArray(svg));
check(widget.renderer().isValid(), "QSvgWidget did not load SVG bytes");
check(widget.sizeHint.width() === 32 && widget.sizeHint.height() === 24,
      "QSvgWidget sizeHint conversion failed");
widget.setOptions(new QtSvg.Options(QtSvg.AssumeTrustedSource));
check((widget.options().valueOf() & QtSvg.AssumeTrustedSource.valueOf()) !== 0,
      "QSvgWidget options did not round-trip");

var scene = new QGraphicsScene();
var item = new QGraphicsSvgItem();
item.setSharedRenderer(renderer);
item.setElementId("marker");
item.setCachingEnabled(true);
check(item.isCachingEnabled(), "QGraphicsSvgItem caching flag did not round-trip");
check(item.boundingRect().width() > 0, "QGraphicsSvgItem has no marker bounds");
scene.addItem(item);
check(scene.items().length === 1, "QGraphicsSvgItem was not accepted by QGraphicsScene");
scene.removeItem(item);
delete item;
widget.close();

print("SVG and SVG Widgets smoke test passed");
